warc_spec: https://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.0/
max_warc_size: 512000000  # 512mb

collection: links # collection name
description: Get all links  # collection description
operator: vginsights # operator email address
robots: vginsights  # robots policy (obey or ignore)
user_agent: vginsights # your user-agent
warc_prefix: .warc # WARC filename prefix
warc_dest: ./data # WARC files destination